### ISSUE TITLE
Camera Ready PR Train

### ISSUE THREAD

**Issue by vincekurtz** [ToyotaResearchInstitute/idto#5]
Todo list for getting this repo cleaned up and ready to use as the main public-facing IDTO implementation, replacing https://github.com/vincekurtz/drake/tree/traj_opt. 

- [x] Deprecation fixes (#1) 
- [x] Add a `LICENSE` (#7)
- [x] Reorganize (#2)
- [x] Fix and document `scripts` (#8 )
- [x] Add basic linting (#4)
- [x] Update examples to use parameters in the paper (#6)
- [ ] Improve READMEs
    - [x] Remove outdated install instructions (#3)
    - [x] Update the top-level README (#9)
    - [ ] Add per-example READMEs
- [ ] Create a pinned version for the paper
- [x] Document review process/contributing guidelines (#10)
- [ ] CI?

**Comment by vincekurtz** [comment]
Closing this for now as remaining items are non-essential
